import{a as c,i as u}from"./assets/vendor-2dcf4ad5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))s(n);new MutationObserver(n=>{for(const r of n)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function a(n){const r={};return n.integrity&&(r.integrity=n.integrity),n.referrerpolicy&&(r.referrerPolicy=n.referrerpolicy),n.crossorigin==="use-credentials"?r.credentials="include":n.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(n){if(n.ep)return;n.ep=!0;const r=a(n);fetch(n.href,r)}})();c.defaults.headers.common["x-api-key"]="live_oSINAuIL5VeXPZdbvcxtlq0EkN8PZNKc0mxfdrsdea4ju9clPwyFoZ9g0X0IN5Ib";function f(){return c.get("https://api.thecatapi.com/v1/breeds").then(function(e){return e.data}).catch(function(e){throw console.log(e),e})}function m(e){return c.get(`https://api.thecatapi.com/v1/images/search?breed_=ids${e}`).then(function(t){return t.data}).catch(function(t){console.log(t)})}const i="visually-hidden",o={breeds:document.querySelector(".breed-select"),catInfo:document.querySelector(".cat-info"),loader:document.querySelector(".loader"),hiddenBreeds(){this.breeds.classList.add(i)},unhiddenBreeds(){this.breeds.classList.remove(i)},hiddenCatInfo(){this.catInfo.classList.add(i)},unhiddenCatInfo(){this.catInfo.classList.remove(i)},hiddenLoader(){this.loader.classList.add(i)},unhiddenLoader(){this.loader.classList.remove(i)}};let l=[];o.hiddenBreeds();f().then(e=>{l=e,e.forEach(t=>{p(t)}),o.hiddenLoader(),o.unhiddenBreeds()}).catch(e=>{console.error(e),o.hiddenLoader(),h()});function p(e){const t=`<option value="${e.id}">${e.name}</option>`;o.breeds.insertAdjacentHTML("beforeend",t)}o.breeds.addEventListener("change",()=>{const e=o.breeds.value;o.hiddenCatInfo(),o.unhiddenLoader(),m(e).then(t=>{if(t.length===0)throw new Error("No image");o.hiddenLoader(),o.unhiddenCatInfo(),g(t[0],e)}).catch(t=>{console.log(t),o.hiddenLoader(),o.hiddenBreeds(),h()})});function g(e,t){const{url:a}=e,{name:s,description:n,temperament:r}=y(t);console.log(e);const d=`
    <img class="cat-image" alt="cat" src=${a} width=400px height=400px></img>
    <div class="body__internal-wrapper">
      <h2 class="body__head2">${s}</h2>
      <p class="body__p-description">${n}</p>
      <h3 class="body__head3-temperament">Temperament:</h3>
      <p class="body__p-temperament">${r}</p>
    </div>`;o.catInfo.innerHTML=d}function y(e){return l.find(t=>t.id===e)}function h(){u.error({message:"Oops! Something went wrong! Try reloading the page!",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
